# Generated by Django 5.1.3 on 2024-11-13 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 'expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 'income'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
        migrations.CreateModel(
            name='EMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'expense'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
