# Generated by Django 5.1.3 on 2024-11-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_type_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('emi', 'EMI')], default='expense', max_length=10),
        ),
        migrations.AlterField(
            model_name='emi',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 'emi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.category'),
        ),
    ]
