# Generated by Django 5.1.3 on 2024-11-18 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_customuser_alter_category_user_alter_emi_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
