# Generated by Django 5.1.3 on 2024-11-21 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='remaining_installments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emi',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='emi',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emi',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='active', max_length=20),
        ),
    ]
