# Generated by Django 5.1.3 on 2024-11-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_category_name_alter_category_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('emi', 'EMI')], max_length=20),
        ),
    ]
