# Generated by Django 5.1.3 on 2024-11-30 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='next_payment_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='emi',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
